### ISSUE TITLE
Can't get it to use Front/Rear Camera dependency property

### ISSUE THREAD

**Issue by Tam66662** [vtserej/Camera2Forms#1]
In the CameraPage.xaml, you have the Camera dependency property set to "Rear".  But when I try to change it to "Front", nothing changes...I'm still seeing the same camera visualization.  

P.S. Great work, by the way!  I'm at least able to get better control of the camera with your example.

**Comment by vtserej** [comment]
@Tam66662  check latest commit and see if it works

**Comment by Tam66662** [comment]
Thanks, I can confirm that the camera changes now when I set the xaml value to "Rear" or "Front".
