### ISSUE TITLE
Why does Camera2 ControlAfState alternate between null and 2 for Samsung 8 CameraCaptureListener.Process?

### ISSUE THREAD

**Issue by WillAutioItrax** [vtserej/Camera2Forms#11]
I am working with a variation on this code. Things were working OK on the Samsung 7 that I had for testing. Then I tried it on a Samsung 8. I got as far as CameraCaptureListener.Process and it crashed on a null exception.
Here is a snippet of the code:

`           
            switch (owner.mState)
            {                
                case CameraDroid.STATE_WAITING_LOCK:
                    {
                        Integer afState = (Integer)result.Get(CaptureResult.ControlAfState);

                        if (afState == null)
                        {
                            System.Diagnostics.Debug.WriteLine(" ** CameraCaptureListener Process STATE_WAITING_LOCK" +
                                " - afState=null");
                        }
                        else
                        {
                            System.Diagnostics.Debug.WriteLine(" ** CameraCaptureListener Process STATE_WAITING_LOCK - afState= "
                                + afState.IntValue());
                        }

                        if (owner.SelectedCamera.HasAutoFocus == false) 
                        {
                            System.Diagnostics.Debug.WriteLine(" ** CameraCaptureListener HasAutoFocus == false");
                            owner.mState = CameraDroid.STATE_PICTURE_TAKEN;
                            owner.TakePhoto();
                        }
                        else if (afState == null) // Note: this is the main part that was added in
                        {
                            break;
                        }
                        else if ((((int)ControlAFState.FocusedLocked) == afState.IntValue()) ||
                                   (((int)ControlAFState.NotFocusedLocked) == afState.IntValue()))
                        {
                                // ControlAeState can be null on some devices
                                Integer aeState = (Integer)result.Get(CaptureResult.ControlAeState);

                                if (aeState == null || aeState.IntValue() == ((int)ControlAEState.Converged))
                                {
                                    System.Diagnostics.Debug.WriteLine(" ** CameraCaptureListener Process ControlAEState.Converged pre TakePhoto ");
                                    owner.mState = CameraDroid.STATE_PICTURE_TAKEN;
                                    owner.TakePhoto();
                                }
                                else
                                {
                                    System.Diagnostics.Debug.WriteLine(" ** CameraCaptureListener Process pre RunPrecaptureSequence");
                                    owner.RunPrecaptureSequence();
                                }
                        }
                        break;
                    }
`
When I run this on an S7 it immediately has an afState == 4, carries on and is done nicely.
When I run this on an S8 (Samsung SM G950W on Android 9 - API 28) it comes thru this code a few times alternating between afState is null and afState.IntValue() == 4.

With the code that skips out when afState is null in place, I get a nice preview and can take one picture. After that the preview is so very dark that I can hardly see what the camera is pointing at. I can only see very bright things. BTW, if I take a picture, that all seems to work, but the preview for the next pic is still super dark.

How should I handle the afState == null?
Is there some other code that I should add in?
What is happening in the S8 to cause the alternating null and 2? This is what the output looks like:

    [0:]  ** CameraCaptureListener Process STATE_WAITING_LOCK - afState=null
    [0:]  ** CameraCaptureListener Process STATE_WAITING_LOCK - afState= 2
    [0:]  ** CameraCaptureListener Process STATE_WAITING_LOCK - afState=null
    [0:]  ** CameraCaptureListener Process STATE_WAITING_LOCK - afState= 2
    [0:]  ** CameraCaptureListener Process STATE_WAITING_LOCK - afState=null
    [0:]  ** CameraCaptureListener Process STATE_WAITING_LOCK - afState= 4

Thanks!

**Comment by WillAutioItrax** [comment]
Oops:
afState is null and afState.IntValue() == 4.
should be 
afState is null and afState.IntValue() == 2.

**Comment by vtserej** [comment]
was it fixed?
remember 3 things 
1- Camera2 API was developed by google and every phone maker made their own version, So you can expect to see anything there
2- Xamarin implementation has bugs you can see they didn't even bother to merge the pull requests on the project GitHub  URL
3- The way this camera works is by polling via background thread the camera states. the most important are afState (auto focus state) and after that aeState (auto exposure state) the last one is required for the API to determine if the pictures needs more flash or more time of the lens receiving light.

**Comment by WillAutioItrax** [comment]
@vtserej Thanks for the comments.
The Edit was only to correct a typo in the post.
Still wondering how to deal with the afState of null. 
And what totally surprises me is that it alternates in quick succession between null and 2.

**Comment by WillAutioItrax** [comment]
@vtserej 
After looking at the original code that I based mine on (https://github.com/vtserej/Camera2Forms ) as well as 
https://docs.microsoft.com/en-us/samples/xamarin/monodroid-samples/android50-camera2basic/
I noticed a difference between mine and theirs. I have a line:
`if (owner.SelectedCamera.HasAutoFocus == false) `
and they both have:
`if (afState == null)`
When I make that change, it works better. 
I don't know if it is the final answer, but it works better.
Thanks for your help.
