### ISSUE TITLE
Front Camera

### ISSUE THREAD

**Issue by HosseinTv** [vtserej/Camera2Forms#13]
I use this code : 

        if (CameraPreview.Camera == CameraOptions.Front)
            CameraPreview.Camera = CameraOptions.Rear;
        else
            CameraPreview.Camera = CameraOptions.Front;

and this : 
    <cameraView:CameraPreview  
                    x:Name="CameraPreview"           
                    BackgroundColor="Black"
                    HorizontalOptions="FillAndExpand"
                    Camera="Front"                                         
                    Margin="0,0,0,0"
                    VerticalOptions="FillAndExpand"
                    Grid.Column="0" Grid.Row="0">
            </cameraView:CameraPreview>

but it cant show front camera preview.

**Comment by vtserej** [comment]
check latest commit
