### ISSUE TITLE
How can I set camera options from xamarin xaml

### ISSUE THREAD

**Issue by HosseinTv** [vtserej/Camera2Forms#14]
I use your app for android. 
How can I set camera options from xamarin xaml. 
For example :
I have a button for flash mode,  how can I set ControlAeMode with button click.

**Comment by HosseinTv** [comment]
Is there any way to do it?

**Comment by vtserej** [comment]
You have to add those methods on the CameraPreview class as a command checkout cameraclick command

**Comment by HosseinTv** [comment]
Could you give me a sample code?

**Comment by HosseinTv** [comment]
@vtserej it's complicated for me, could you give me just one code how to set ControlAeMode please?

**Comment by vtserej** [comment]
its a little bit complicated. ControlAeMode has several states

**Comment by HosseinTv** [comment]
I know it has several states, if I know how to set one of them, I will able to set controlAfMode and other options. For now I don't know how to connect CameraPreview to CameraDroid😭
