### ISSUE TITLE
Bug in lensFacing

### ISSUE THREAD

**Issue by tiago-cerveira** [vtserej/Camera2Forms#2]
Hi, there appears to be a bug in the CameraDroid.cs file regarding setting the camera output.

In line 140 souldn't it read "if (facing != null && facing **!=** (Integer.ValueOf((int)lensFacing)))"?

**Comment by vtserej** [comment]
yes you are right it was a fix that I did, this is the code from google.
but when I introduced the code to select the camera from the Xamarin forms I introduced the bug.
Please if you can do a pull request

                    // We don't use a front facing camera in this sample.
                    var facing = (Integer)characteristics.Get(CameraCharacteristics.LensFacing);
                    if (facing != null && facing == (Integer.ValueOf((int)LensFacing.Front)))
                    {
                        continue;
                    }
