### ISSUE TITLE
Back Camera on Samsung S10

### ISSUE THREAD

**Issue by nilanga2019** [vtserej/Camera2Forms#3]
Great work, thanks a lot.
I have tried using a Samsung S9 and it works fine on both Front and Rear cameras.
Unfortunately on S10 the Rear camera does not work, the _camera.Photo event does not get fired.

**Comment by vtserej** [comment]
Yes, I know that issue.
The thing is S10 has 2 rear cameras. One is a fish eye camera wish it doesn't help too much.
the solution is in SetCameraOutputs to select the one that contains Flash.

**Comment by nilanga2019** [comment]
Thank you for your help, problem solved. Once again great work.
