### ISSUE TITLE
CameraClick.Execute crashed

### ISSUE THREAD

**Issue by rocket-ch** [vtserej/Camera2Forms#8]
Executing "CameraPreview.CameraClick.Execute(null);" leads to the following error:

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object. occurred

how to solve this issue?

feedback welcome :)

**Comment by vtserej** [comment]
phone model

**Comment by rocket-ch** [comment]
using an android emulator, running a Pixel 2 XL with API 27.

another question i have is, what  should be triggered when executing "CameraPreview.CameraClick.Execute(null);" triggers?

**Comment by vtserej** [comment]
emulators do not provide camera access

**Comment by rocket-ch** [comment]
the same issue still exists executing on a Samsung Galaxy S6, API 28....

any ideas how to solve? 

another question i have is, what should be triggered when executing "CameraPreview.CameraClick.Execute(null);"? 
=> currently the property get-accessor of "CameraClick" is executed, which returns a not initalized "camerClick" value (or do i understand something wrong?)

**Comment by vtserej** [comment]
Did you copy my code into yours?
Did youbset the permision values on the manifest?

**Comment by vtserej** [comment]
you have to debug the underlying classes in android especially cameradroid.cs
you need to see what happens when you try to open the camera 

`        private void SetUpCameraOutputs(int width, int height)
        {
            _manager = (CameraManager)_context.GetSystemService(Context.CameraService);

            string[] cameraIds = _manager.GetCameraIdList();

            _cameraId = cameraIds[0];

            for (int i = 0; i < cameraIds.Length; i++)
            {
                CameraCharacteristics chararc = _manager.GetCameraCharacteristics(cameraIds[i]);

                var facing = (Integer)chararc.Get(CameraCharacteristics.LensFacing);
                if (facing != null && facing == (Integer.ValueOf((int)lensFacing)))
                    continue;

                _cameraId = cameraIds[i];
            }

            var characteristics = _manager.GetCameraCharacteristics(_cameraId);
            var map = (StreamConfigurationMap)characteristics.Get(CameraCharacteristics.ScalerStreamConfigurationMap);

            if (_supportedJpegSizes == null && characteristics != null)
            {
                _supportedJpegSizes = ((StreamConfigurationMap)characteristics.Get(CameraCharacteristics.ScalerStreamConfigurationMap)).GetOutputSizes((int)ImageFormatType.Jpeg);
            }

            if (_supportedJpegSizes != null && _supportedJpegSizes.Length > 0)
            {
                _idealPhotoSize = GetOptimalSize(_supportedJpegSizes, 1050, 1400); //MAGIC NUMBER WHICH HAS PROVEN TO BE THE BEST
            }

            _imageReader = ImageReader.NewInstance(_idealPhotoSize.Width, _idealPhotoSize.Height, ImageFormatType.Jpeg, 1);

            var readerListener = new ImageAvailableListener();

            readerListener.Photo += (sender, buffer) =>
            {
                Photo?.Invoke(this, buffer);
            };

            var available = (Java.Lang.Boolean)characteristics.Get(CameraCharacteristics.FlashInfoAvailable);
            if (available == null)
            {
                _flashSupported = false;
            }
            else
            {
                _flashSupported = (bool)available;
            }

            _imageReader.SetOnImageAvailableListener(readerListener, _backgroundHandler);

            _previewSize = GetOptimalSize(map.GetOutputSizes(Class.FromType(typeof(SurfaceTexture))), width, height);
        }

        public void OpenCamera(int width, int height)
        {
            if (_context == null || OpeningCamera)
            {
                return;
            }

            OpeningCamera = true;

            SetUpCameraOutputs(width, height);

            _manager.OpenCamera(_cameraId, _cameraStateListener, null);
        }`

**Comment by rocket-ch** [comment]
thanks for your valuable support. 
but i found another solution which works perfect.

**Comment by vtserej** [comment]
care to share the link?

**Comment by rocket-ch** [comment]
i got some hints from a friend. therefore there is no link yet...
