### ISSUE TITLE
How to select photos from phone 

### ISSUE THREAD

**Issue by shahbikash** [vtserej/Camera2Forms#9]
Hi,

First of thanks for the code base, currently we can only take pics using the camera. Its a very common scenario to also select existing pics from the mobile. It would be great if you could point me in the right direction towards implementing it.
Thanks again!!!

**Comment by FuyukiSakura** [comment]
Hi @shahbikash ,

First of all you got the save the image. Which you put 

```csharp
File.WriteAllBytes("where you want to save", imgSource);
```

in the `OnPhoto` method.

Then you just access to photos like you usually do to other files.
